import Head from "next/head";
import dynamic from "next/dynamic";

const Intro = dynamic(() => import("containers/intro"), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>RCA IED 2023: Royal College of Art Information Expereience Design Public Event</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, width=device-width, height=device-height, target-densitydpi=device-dpi" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Intro />

      {/* <Main /> */}
    </>
  );
}
