import Head from "next/head";
import dynamic from "next/dynamic";

const QuestionMap = dynamic(() => import("containers/question-map"));

export default function Page() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, width=device-width, height=device-height, target-densitydpi=device-dpi" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Main /> */}
      <QuestionMap />
    </>
  );
}
